.cache: &cache
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - .tox
      - eenv/

before_script:
    - echo "HOME is $HOME"
    - "[ -f $HOME/.gitlab_runner.sh ] && . $HOME/.gitlab_runner.sh"
    - "[ -s 'eenv/bin/activate' ] || virtualenv -p $(pyenv which python3) eenv"
    - "basedir=$(pwd)"

tox:
  <<: *cache
  tags:
    - shell
  stage: test
  allow_failure: false
  script:
    - python -m pip install -U pip
    - python -m pip install tox
    - "which python ; pyenv which python ; true"
    - "which tox ; true"
    - python -m tox

flake:
  tags:
    - shell
  stage: test
  allow_failure: false
  script:
    - "source eenv/bin/activate"
    - "echo python is $(which python)"
    - "python -m pip install -r requirements.txt flake8"
    - "python -m flake8 timon setup.py --exclude timon/webclient"

webif1_test:
  tags:
    - shell
  stage: test
  allow_failure: false
  script:
    - "echo basedir is $basedir"
    - "cd timon/webclient/webif1 ; . $HOME/.nvm/nvm.sh ; nvm use ; cd ../../.."
    - pwd
    - npm install
    - npm run lint
    - npm test

