name: Timon CI

on:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
        - uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64
        - name: install dependencies
          run: |
            python -m pip install -U pip
            python -m pip install flake8
        - name: check import order
          if: ${{ matrix.python-version == '3.11' }}
          run: |
            python -m pip install isort
            python -m isort --show-files setup.py timon
            python -m isort --diff --check setup.py timon
        - name: flake
          if: ${{ matrix.python-version < 'pypy' }}
          run: |
            python -m flake8 timon setup.py --exclude timon/webclient
        - name: pytest
          run: |
            python -m pip install -r requirements/tox.txt
            pytest

